@Server_HostAddress = http://localhost:5186

###
GET {{Server_HostAddress}}/products/hr
Accept: application/json

###
GET {{Server_HostAddress}}/products/hr/1
Accept: application/json

###
GET {{Server_HostAddress}}/auth/
Accept: application/json

###
