@Server_HostAddress = https://localhost:7057

###
GET {{Server_HostAddress}}/products/hr
Accept: application/json

###
GET {{Server_HostAddress}}/products/de/3
Accept: application/json

###
GET {{Server_HostAddress}}/nopassword/info@vina-ivanic.hr
Accept: application/json

###
GET {{Server_HostAddress}}/nopassword/zohoredirect?code=12345&location=us&accounts-server=accsrv
Accept: application/json
